<?php

namespace frontned\modules\api\v1;

use yii\db\ActiveRecord;

class WashMachine extends ActiveRecord
{
    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }
}
