<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activate' => 'Активувати',
    'Basket' => 'Кошик',
    'Cancel' => 'Відмінити',
    'Create' => 'Створити',
    'Create user' => 'Створити користувача',
    'Content' => 'Вміст',
    'Companies' => 'Компанії',
    'Email' => 'Емейл',
    'Female' => 'Жінка',
    'Other' => 'Інший',
    'Password' => 'Пароль',
    'Position' => 'Посада',
    'Roles' => 'Роль',
    'Save' => 'Зберегти',
    'Status' =>'Статус',
    'Static pages' => 'Статичні сторінки',
    'System' => 'Система',
    'Update' => 'Редагувати',
    'Update user' => 'Редагувати користувача',
    'Update user: {username}' => 'Редагувати користувача: {username}',
    'Username' => 'Ім\'я користувача',
    'Users' => 'Користувачі',
    'Main' => 'Головна',
    'Male' => 'Чоловік',
    'Menu' => 'Меню',
    'administrator' => 'Адміністратор',
    'financier' => 'Фінанси',
    'technician' => 'Технік',
    'Cards' => 'Картки',
    'Card no' => 'Номер картки',
    'Balance' => 'Баланс',
    'Discount' => 'Скидка',
    'Status' => 'Статус',
];
