<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access' => 'Доступ',
    'Actions' => 'Дії',
    'Active' => 'Активний',
    'Administration' => 'Адміністрування',
    'All' => 'Усі',
    'Avatar' => 'Аватарка',
    'Birthday' => 'Дата народження',
    'Category' => 'Категорія',
    'Delete Confirmation' => 'Ви впевнені, що хочете видалити цей запис?',
    'Inactive' => 'Неактивний',
    'Firstname' => 'Ім\'я',
    'Fistname Lastname Patronymic' => 'Імя, Призвіще. По-Батькові',
    'Gender' => 'Стать',
    'Lastname' => 'Прізвище',
    'Name' => 'Ім\'я',
    'Number' => '№',
    'Other' => 'Інше',
    'Position' => 'Посада',
    'Server Rights' => 'Права на сервері',
    'Status' => 'Статус',
    'Worker Card' => 'Картка співробітника',
    'Undefined' => 'Не визначений',
];