<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access' => 'Доступ',
    'Access Forbidden or user not exist' => 'Доступ заборонений або користувач не інує',
    'Access denied' => 'Доступ заборонений',
    'Actions' => 'Дії',
    'Active' => 'Активний',
    'Administration' => 'Адміністрування',
    'All' => 'Усі',
    'April' => 'Квітень',
    'August' => 'Серпень',
    'Avatar' => 'Аватарка',
    'Back' => 'Назад',
    'Birthday' => 'Дата народження',
    'Category' => 'Категорія',
    'December' => 'Грудень',
    'Delete Confirmation' => 'Ви впевнені, що хочете видалити цей запис?',
    'Entity not found' => 'Ентіті не знайдено',
    'Inactive' => 'Неактивний',
    'Invalid Array [Key => Value] Configuration' => 'Невірна конфігурація [ключ=>значення]',
    'February' => 'Лютий',
    'Firstname' => 'Ім\'я',
    'Fistname Lastname Patronymic' => 'Імя, Призвіще. По-Батькові',
    'Gender' => 'Стать',
    'January' => 'Січень',
    'July' => 'Липень',
    'June' => 'Червень',
    'Lastname' => 'Прізвище',
    'Login via Fb' => 'Вхід/Реєстрація через Facebook',
    'Login via Google' => 'Вхід/Реєстрація через Google',
    'Logo' => 'Логотип',
    'March' => 'Березень',
    'May' => 'Травень',
    'Name' => 'Ім\'я',
    'Not Set' => 'Не визначено',
    'Not found' => 'Не знайдено',
    'November' => 'Листопад',
    'Number' => '№',
    'October' => 'Жовтень',
    'Other' => 'Інше',
    'Position' => 'Посада',
    'September' => 'Вересень',
    'Server Rights' => 'Права на сервері',
    'Status' => 'Статус',
    'Tel.' => 'тел.',
    'Type address' => 'введіть адресу',
    'Type imei' => 'введіть імей',
    'Worker Card' => 'Картка співробітника',
    'Undefined' => 'Не визначений',
    'Unknown' => 'Невідомо',
    'Card inactive' => 'Картка неактивна',
    'Card active' => 'Картка активна',
];
