<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Payment' => 'Поповнення картки',
    'card_no' => 'Номер картки',
    'amount' => 'Сума поповнення',
    'operation time' => 'Время операции',
    'description' => 'Привіт! Ти переказуєшь гроші на свою розрахункову картку Мережі пралень "Постірай-Ка!". Чистота - це те що треба!',
    'Operation' => 'Операция',
    'Operation payment' => 'Оплата',
    'Operation income' => 'Пополнение',
    'Operation fail' => 'Помилка',
];
