<?php

namespace frontend\modules\api\v1\models;

use yii\db\ActiveRecord;

class WashMachine extends ActiveRecord
{
    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }
}
