<?php

namespace backend\models\search;

use Yii;
use yii\base\Model;
use frontend\models\CustomerCards;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for Cards search.
 */
class CardSearch extends CustomerCards
{
    const RECORDS_PER_PAGE = 20;

    public function rules()
    {
        return [
            [['card_no', 'discount', 'status', 'created_at'], 'integer'],
            [['balance'], 'number'],
        ];
    }

    public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($params)
    {
        $query = CustomerCards::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => self::RECORDS_PER_PAGE
            ],
        ]);

        if ( !($this->load($params) && $this->validate()) ) {
            return $dataProvider;
        }

        $query->andFilterWhere([
            'card_no' => $this->card_no,
            'balance' => $this->balance,
            'discount' => $this->discount,
            'status' => $this->status,
            'created_at' => $this->created_at,
        ]);

        return $dataProvider;
    }
}
