<?php

namespace backend\models\search;

use Yii;
use yii\base\Model;
use frontend\models\CustomerCards;
use frontend\models\Transactions;
use frontend\models\Imei;
use frontend\models\AddressImeiData;
use frontend\models\AddressBalanceHolder;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use frontend\services\globals\Entity;

/**
 * This is the model class for Cards search.
 */
class CardSearch extends CustomerCards
{
    const RECORDS_PER_PAGE = 20;
    const DATE_FORMAT = 'd-m-y H:i';

    public function rules()
    {
        return [
            [['card_no', 'discount', 'status', 'created_at'], 'integer'],
            [['balance'], 'number'],
        ];
    }

    public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    /**
     * Main search method
     * 
     * @return yii\data\ActiveDataProvider
     */
    public function search($params)
    {
        $query = CustomerCards::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => self::RECORDS_PER_PAGE
            ],
            'sort' => [
                'defaultOrder' => ['status' => SORT_DESC]
            ]
        ]);

       

        if ( !($this->load($params) && $this->validate()) ) {

            return $dataProvider;
        }

        $query->andFilterWhere([
            'card_no' => $this->card_no,
            'balance' => $this->balance,
            'discount' => $this->discount,
            'status' => $this->status,
            'created_at' => $this->created_at,
        ]);

        return $dataProvider;
    }

    /**
     * Search user method
     * 
     * @return yii\data\ActiveDataProvider
     */
    public function searchUser($params)
    {
        $query = CustomerCards::find()->select(['user_id'])->distinct()->andWhere(['not', ['user_id' => null]]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => self::RECORDS_PER_PAGE
            ]
        ]);

        if ( !($this->load($params) && $this->validate()) ) {
            return $dataProvider;
        }

        $query->andFilterWhere([
            'user_id' => $this->user_id,
        ]);

        return $dataProvider;
    }

    /**
     * Main search pertain company method
     * 
     * @param int $companyId
     * @param array $params
     * 
     * @return yii\data\ActiveDataProvider
     */
    public function searchPertainCompany($companyId, $params)
    {
        $dataProvider = $this->search($params);
        $dataProvider->query->andWhere(['company_id' => $companyId]);

        return $dataProvider;
    }

    /**
     * Search user  pertain company method
     * 
     * @param int $companyId
     * @param array $params
     * 
     * @return yii\data\ActiveDataProvider
     */
    public function searchByUserId($userId, $params)
    {
        $cardNos = $this->findCardsByUserId($userId);
        $dataProvider = $this->search($params);
        $dataProvider->query->andWhere(['card_no' => $cardNos]);

        return $dataProvider;
    }

    /**
     * Search user pertain company method
     * 
     * @param int $companyId
     * @param array $params
     *
     * @return yii\data\ActiveDataProvider
     */
    public function searchUserPertainCompany($companyId, $params)
    {
        $dataProvider = $this->searchUser($params);
        $dataProvider->query->andWhere(['company_id' => $companyId]);

        return $dataProvider;
    }

    /**
     * Finds address by card number
     * 
     * @param int $cardNo
     * @param frontend\models\Transactions $transaction
     * 
     * @return string|null
     */
    public function findAddressByCardNo($cardNo, $transaction = null)
    {
        if (empty($transaction) && empty($transaction = Transactions::findLastTransactionByCardNo($cardNo, 'imei'))) {

            return null;
        }

        $imei = Imei::find()->andWhere(['imei' => $transaction->imei])->limit(1)->one();
        $addressImeiData = new AddressImeiData();

        if (empty($imei->id)) {

            return null;
        }

        $address_id = $addressImeiData->findAddressIdByImeiAndTimestamp($imei, time());

        if (empty($address_id)) {

            return null;
        }

        $address = AddressBalanceHolder::find()->where(['id' => $address_id])->limit(1)->one();

        if (empty($address)) {

            return null;
        }

        return $address->address;
    }

    /**
     * Finds last transaction date by card number
     * 
     * @param int $cardNo
     * 
     * @return string|null
     */
    public function findLastActivityByCardNo($cardNo)
    {
        $transaction = Transactions::findLastTransactionByCardNo($cardNo, 'created_at');

        if (empty($transaction)) {

            return null;
        }

        return date(self::DATE_FORMAT, $transaction->created_at);
    }

    /**
     * Finds card numbers by user id
     * 
     * @param int $userId
     * 
     * @return array
     */
    public function findCardsByUserId($userId)
    {
        $entity = new Entity();
        $companyId = $entity->getCompanyId();
        $query = CustomerCards::find()->select(['card_no'])->andWhere(
            ['user_id' => $userId, 'company_id' => $companyId]
        );
        $items = $query->all();

        return array_unique(ArrayHelper::getColumn($items, 'card_no'));
    }
}
