<?php

namespace frontend\models;

class CbLogSearch extends CbLog
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($param)
    {
        $entity = new Entity();
        $imeiIds = ImeiData::find()->select('imei_id')->distinct()->all();
        $imeiIds = ArrayHelper::getColumn($imeiIds, 'imei_id');

        $query = Imei::find()->andWhere(['imei.company_id' => $entity->getCompanyId(), 'imei.id' => $imeiIds]);
    }

}
