<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access' => 'Доступ',
    'Access Forbidden or user not exist' => 'Доступ запрещен или пользователь не существует',
    'Actions' => 'Действия',
    'Active' => 'Активный',
    'Administration' => 'Администрирование',
    'All' => 'Все',
    'Author' => 'Автор',
    'Avatar' => 'Аватар',
    'Banned' => '',
    'Birthday' => 'День рождения',
    'Category' => 'Категория',
    'Comment' => 'Комментарий',
    'Created at' => 'Время создания',
    'Deleted' => '',
    'Delete Confirmation' => 'Вы уверены, что хотите удалить эту запись?',
    'Description' => 'Описание',
    'Email' => '',
    'Entity not found' => 'Энтити не найдено',
    'Firstname' => 'Имя',
    'Fistname Lastname Patronymic' => 'Имя, фамилия, отчество',
    'Frequency' => 'Частота',
    'Gender' => 'Пол',
    'Inactive' => 'Неактивный',
    'Invalid Array [Key => Value] Configuration' => 'Неверная конфигурация [ключ=>значение]',
    'Key' => 'Ключ',
    'Keywords' => 'Ключевые слова',
    'Last action at' => 'Активность',
    'Lastname' => 'Фамилия',
    'Link' => 'Ссылка',
    'Logo' => 'Логотип',
    'Name' => 'Имя',
    'Not Set' => 'Не установлено',
    'Number' => '№',
    'Other' => 'Прочее',
    'Parent' => 'Родитель',
    'Password' => 'Пароль',
    'Preview' => 'Анонс',
    'Published at' => 'Время публикации',
    'Position' => 'Должность',
    'Remember me' => 'Запомнить меня',
    'Server Rights' => 'Права на сервере',
    'Slug' => 'ЧПУ',
    'Sort index' => 'Индекс сортировки',
    'Status' => 'Статус',
    'Tags' => 'Теги',
    'Text' => 'Текст',
    'Title' => 'Название',
    'Type imei' => 'введите имей',
    'Undefined' => 'Не определенный',
    'Updated at' => 'Время обновления',
    'Updater' => 'Обновивший',
    'Username' => 'Имя пользователя',
    'Username or email' => 'Имя пользователя или email',
    'Value' => 'Значение',
    'Website' => 'Веб-сайт',
    'Worker Card' => 'Картка сотрудника',
];